# Form implementation generated from reading ui file 'err.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Errorbox(object):
    def setupUi(self, Errorbox):
        Errorbox.setObjectName("Errorbox")
        Errorbox.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        Errorbox.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Errorbox)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Errorbox)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 60, 341, 151))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(Errorbox)
        self.label.setGeometry(QtCore.QRect(30, 10, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label.setObjectName("label")
        self.err_reason = QtWidgets.QLabel(Errorbox)
        self.err_reason.setGeometry(QtCore.QRect(33, 210, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.err_reason.setFont(font)
        self.err_reason.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.err_reason.setObjectName("err_reason")

        self.retranslateUi(Errorbox)
        self.buttonBox.accepted.connect(Errorbox.accept)
        self.buttonBox.rejected.connect(Errorbox.reject)
        QtCore.QMetaObject.connectSlotsByName(Errorbox)

    def retranslateUi(self, Errorbox):
        _translate = QtCore.QCoreApplication.translate
        Errorbox.setWindowTitle(_translate("Errorbox", "Dialog"))
        self.plainTextEdit.setPlainText(_translate("Errorbox", "Error Message "))
        self.label.setText(_translate("Errorbox", "Error!"))
        self.err_reason.setText(_translate("Errorbox", "Reason"))
