# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(318, 326)
        MainWindow.setMinimumSize(QtCore.QSize(318, 326))
        MainWindow.setMaximumSize(QtCore.QSize(318, 326))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.screen = QtWidgets.QLCDNumber(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(0, 0, 311, 211))
        font = QtGui.QFont()
        font.setBold(True)
        self.screen.setFont(font)
        self.screen.setObjectName("screen")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 210, 311, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.horizontalLayout.addWidget(self.input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.con = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.con.setFont(font)
        self.con.setObjectName("con")
        self.verticalLayout.addWidget(self.con)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menus = QtWidgets.QMenuBar(MainWindow)
        self.menus.setGeometry(QtCore.QRect(0, 0, 318, 22))
        self.menus.setObjectName("menus")
        self.help = QtWidgets.QMenu(self.menus)
        self.help.setObjectName("help")
        MainWindow.setMenuBar(self.menus)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.about = QtGui.QAction(MainWindow)
        self.about.setObjectName("about")
        self.version = QtGui.QAction(MainWindow)
        self.version.setObjectName("version")
        self.more = QtGui.QAction(MainWindow)
        self.more.setObjectName("more")
        self.help.addAction(self.about)
        self.menus.addAction(self.help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "人数："))
        self.input.setText(_translate("MainWindow", "48"))
        self.con.setText(_translate("MainWindow", "生  成"))
        self.help.setTitle(_translate("MainWindow", "帮助"))
        self.about.setText(_translate("MainWindow", "关于"))
        self.version.setText(_translate("MainWindow", "版本信息"))
        self.more.setText(_translate("MainWindow", "批量生成"))
