# This is a basic workflow to help you get started with Actions

name: 添加Online Update UI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Ui_change
        run: |
          pip install pyqt5-tools
          cd ./program
          pyuic5.exe -o ./about.py ./about.ui
          pyuic5.exe -o ./err.py ./errbox.ui
          pyuic5.exe -o ./window.py ./rand.ui
      
