# This is a basic workflow to help you get started with Actions

name: Release CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get current time
        uses: 1466587594/current-time@v1
        id: current-time
        with:
          format: YYYYMMDD_HHmmss
          utcOffset: "+08:00"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Install Pkgs
        run: |
          pip install PyQt5
      - name: Build_exe
        run: |
          pip install pyinstaller
          cd ./program
          pyinstaller.exe -w -n qimrand ./main.py 
      - name : Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: qimrand_build_${{ steps.current-time.outputs.formattedTime }}
          path: |
            ./program/dist/*
      - name: Build exe for CI Debug
        run: |
          cd ./program
          pyinstaller.exe -F -n qimrand ./main.py 
      - name : Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: qimrand_debug_${{ steps.current-time.outputs.formattedTime }}
          path: |
            ./program/*.exe
        
      
